ARG BASE_IMAGE=cgr.dev/chainguard/wolfi-base:latest
ARG MMMCP_IMAGE=ghcr.io/obot-platform/mmmcp:latest

FROM ${MMMCP_IMAGE} AS mmmcp
FROM ${BASE_IMAGE}

USER root

COPY --from=mmmcp /usr/local/bin/mmmcp /usr/local/bin/
COPY ./scripts/mmmcp.sh /usr/local/bin/mmmcp.sh

RUN apk add jq && chmod +x /usr/local/bin/mmmcp.sh

RUN mkdir -p /home/user/.local/bin && chown -R 1000:0 /home/user && chown -R 1000:0 /usr/local

USER 1000

ENV HOME=/home/user

WORKDIR /home/user

ENV PATH="/home/user/.local/bin:$PATH"

ENTRYPOINT ["mmmcp.sh"]
