ARG GITHUB_IMAGE=ghcr.io/github/github-mcp-server:latest
ARG MMMCP_IMAGE=ghcr.io/obot-platform/mmmcp:v0.1.1

FROM ${GITHUB_IMAGE} AS binary

FROM ${MMMCP_IMAGE}

COPY --from=binary /server/github-mcp-server .

USER root

RUN cat > mmmcp.yaml <<'EOF'
servers:
  - name: GitHub
    command: ./github-mcp-server
    args: [stdio]
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      GITHUB_TOOLSETS: ${GITHUB_TOOLSETS}
      GITHUB_DYNAMIC_TOOLSETS: ${GITHUB_DYNAMIC_TOOLSETS}
      GITHUB_HOST: ${GITHUB_HOST}
EOF

RUN chown 1000 mmmcp.yaml

ENTRYPOINT ["mmmcp"]

CMD ["--listen", ":8099", "--config", "./mmmcp.yaml"]

USER 1000
